{{- $networkPoliciesEnabled := false -}}
{{- if .Values.global -}}
{{- if .Values.global.networkPolicyEnabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}

{{ if $networkPoliciesEnabled }}
{{ $components:= list "api-gateway" "fusion-admin" "query-pipeline" "fusion-indexing" "fusion-features" "job-rest-server" "connectors-classic" "connectors-backend" "connectors" "fusion-jupyter" "config-sync"}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fusion.fusion-features.fullname" .  }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component:  "fusion-features"
      app.kubernetes.io/part-of: "fusion"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
{{- range $component := $components }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "{{ $component }}"
{{- end }}
      - podSelector:
          matchLabels:
            spark-role: driver
      - podSelector:
          matchLabels:
            spark-role: executor
      ports:
      - protocol: TCP
        port: 8769
{{ if .Values.networkPolicy.additionalIngressRules }}
{{ toYaml .Values.networkPolicy.additionalIngressRules | nindent 4 }}
{{ end }}
  egress:
# Define egress for DNS lookups
    - to: {{ .Values.networkPolicy.dnsAccess | toYaml | nindent 8 }}
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
# This outbound rule is required to talk to the kubernetes API services
    - to: {{ .Values.networkPolicy.kubernetesAccess | toYaml | nindent 8 }}
      ports:
      - protocol: TCP
        port: 443
    - to:
      - podSelector:
          matchLabels:
            app: "zookeeper"
      ports:
      - protocol: TCP
        port: 2181
      - protocol: TCP
        port: 2281
    - to:
      - podSelector:
          matchLabels:
            app: "logstash"
      ports:
      - protocol: TCP
        port: 9600
      - protocol: TCP
        port: 4560
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: "solr"
      ports:
      - protocol: TCP
        port: 8983
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "fusion-admin"
      ports:
        - protocol: TCP
          port: 8765
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "fusion-features"
      ports:
      - protocol: TCP
        port: 8769
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "ml-model-service"
      ports:
      - protocol: TCP
        port: 8086
      - protocol: TCP
        port: 6565
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "api-gateway"
      ports:
      - protocol: TCP
        port: 6764
    - to:
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "query-pipeline"
      ports:
      - protocol: TCP
        port: 8787
    - to:
      - podSelector:
          matchLabels:
            component: "broker"
      ports:
        - protocol: TCP
          port:  6650
        - protocol: TCP
          port:  8080
        - protocol: TCP
          port:  6651
        - protocol: TCP
          port:  8443
    - to: 
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: "milvus"
      ports:
        - protocol: TCP
          port: 19121
        - protocol: TCP
          port: 19530

{{- if .Values.networkPolicy.additionalEgressRules }}
{{ toYaml .Values.networkPolicy.additionalEgressRules | nindent 4 }}
{{ end }}
{{- end }}
