{{- if .Values.rbac.create -}}

{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ include "fusion.connectors-classic.fullname" . }}"

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ include "fusion.connectors-classic.fullname" . }}"
rules:
  - apiGroups: [""]
    resources: [ "pods", "services", "configmaps", "endpoints" ]
    verbs: [ "get", "list", "watch" ]
{{- if $tlsEnabled }}
  - apiGroups: [ "cert-manager.io" ]
    resources: [ "certificates" ]
    verbs: [ "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get" ]
{{- end }}
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "fusion.connectors-classic.fullname" . }}"
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: "{{ include "fusion.connectors-classic.fullname" . }}"
    apiGroup: ""
roleRef:
  kind: Role
  name: "{{ include "fusion.connectors-classic.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io

{{- end }}
