apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.5.1
description: Lucidworks service for hosting connector plugins
keywords:
- fusion
- connectors
- plugins
- rpc
- v2
maintainers:
- email: matt.mitchell@lucidworks.com
  name: Matt Mitchell
name: connector-plugin
version: 1.0.3
