---

apiVersion: "policy/v1beta1"
kind: "PodDisruptionBudget"
metadata:
  name: "{{ template "fusion.webapps.fullname" . }}"
  labels:
    {{ include "fusion.webapps.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "webapps"
      app.kubernetes.io/part-of: "fusion"
  {{ toYaml .Values.podDisruptionBudget | nindent 2 }}
