---
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}
{{- $jsonOutput := ( eq (include "fusion.loggingJSONOutput" .) "true" ) }}
{{- $logstashHost := (include "fusion.logstashHost" .) -}}
{{- $logPulsar := ( eq (include "fusion.loggingDisablePulsar" .) "false" ) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fusion.api-gateway.fullname" .  }}
  labels: {{ include "fusion.api-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "api-gateway"
      app.kubernetes.io/part-of: "fusion"
  template:
    metadata:
      name: {{ include "fusion.api-gateway.fullname" .  }}
      labels:
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: "api-gateway"
        app.kubernetes.io/part-of: "fusion"
      annotations:
        {{ toYaml .Values.pod.annotations | nindent 8 }}
    spec:
{{- if .Values.securityContext }}
      securityContext:
{{- .Values.securityContext | toYaml | nindent 8 }}
{{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
        {{ tpl (toYaml .Values.affinity) . | nindent 8 }}
    {{- end }}
      volumes:
        - name: "jks"
          secret:
            secretName: "{{ include "fusion.api-gateway.fullname" . }}-jks"
        - name: tmp
          emptyDir: {}
{{- if $tlsEnabled }}
{{ $params := dict "tlsServiceName" ( include "fusion.api-gateway.serviceName" . ) "Release" $.Release "global" $.Values.global "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils }}
{{ include "fusion.tls.volumes" $params | indent 8 }}
{{- end }}
{{- if .Values.additionalVolumes }}
{{- toYaml .Values.additionalVolumes | nindent 8 }}
{{- end }}
        - name: secrets
          secret:
            secretName: service-account-key
            items:
              - key: sa
                path: security.internal.service-account-key
      serviceAccountName: "{{ .Values.rbac.serviceAccountName | default ( include "fusion.api-gateway.fullname" . ) }}"
      imagePullSecrets: {{ toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{ if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{ end }}
      {{ if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{ end }}
      {{ if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{ end }}
      {{ if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{ end }}
      initContainers:
{{- if $tlsEnabled -}}
{{ $params := dict "tlsServiceName" ( include "fusion.api-gateway.serviceName" . ) "Release" $.Release "global" $.Values.global "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils "securityContext" $.Values.securityContext }}
{{ include "fusion.tls.init-container-v2" $params | indent 8 }}
{{- end }}
{{- include "fusion.initContainers.checkZk-v2" . | nindent 8 }}
{{- include "fusion.initContainers.checkPulsar-v2" . | nindent 8 }}
      containers:
{{- if .Values.additionalContainers }}
{{- toYaml .Values.additionalContainers | nindent 6 }}
{{- end }}
      - name: api-gateway
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
        args:
          - "--spring.profiles.active={{ include "fusion.api-gateway.springProfs" . }}{{- if $tlsEnabled }},tls{{- end }}{{- if $jsonOutput }},logjson{{- end }}{{- if $logstashHost }},logstash{{- end }}{{- if $logPulsar }},logpulsar{{- end }}"
          - "--spring.cloud.kubernetes.config.name={{ include "fusion.api-gateway.fullname" . }}"
          - "--spring.cloud.kubernetes.secrets.paths=/etc/secrets"
          - "--spring.cloud.config.enabled=false"
          - "--spring.application.version={{ .Values.image.tag }}"
        {{- if .Values.secrets }}
        envFrom:
          - secretRef:
              name: {{ template "fusion.api-gateway.fullname" . }}
        {{- end }}
        env:
          - name: "COMPONENT"
            value: "api-gateway"
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.javaToolOptions }}
{{- if $tlsEnabled }} -Dlogging.config=classpath:logback-kube-tls.xml {{- else }} -Dlogging.config=classpath:logback-kube.xml {{- end }}
{{- if $tlsEnabled }} -Djavax.net.ssl.trustStore=/etc/fusion/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword={{ .Values.tls.keystorePassword }} -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true -Dzookeeper.ssl.keyStore.location=/etc/fusion/keystores/keystore.jks -Dzookeeper.ssl.trustStore.location=/etc/fusion/keystores/truststore.jks -Dzookeeper.ssl.keyStore.password={{ .Values.tls.keystorePassword }} -Dzookeeper.ssl.trustStore.password={{ .Values.tls.keystorePassword }}{{- end -}}
"
          {{ if $logstashHost }}
          - name: "LOGSTASH_HOST"
            value: "{{ $logstashHost }}"
          {{ end }}
          - name: "PULSAR_TENANT"
            value: "{{ include "fusion.api-gateway.kubeNamespace" . }}"
          - name: "PULSAR_SERVICE_URL"
            value: "{{ include "fusion.api-gateway.pulsarServiceUrl" . }}"
        {{- if .Values.envVars }}
          {{ .Values.envVars | toYaml | nindent 10 }}
        {{- end }}
          - name: "FUSION_VERSION"
            valueFrom:
              configMapKeyRef:
                name: fusion-resources
                key: fusion_version
        ports:
          - containerPort: {{ .Values.port }}
            name: "jetty"
        livenessProbe:
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          httpGet:
            path: /actuator/health
            port: jetty
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          httpGet:
            path: /actuator/health
            port: jetty
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "{{ .Values.preStopSleepTime }}"]
        volumeMounts:
          - name: "jks"
            mountPath: "/etc/ssl/keystores"
{{ if $tlsEnabled }}
          - name: "keystore-volume"
            mountPath: "/etc/fusion/keystores"
{{ end }}
          - name: tmp
            mountPath: /tmp
          - name: secrets
            mountPath: "/etc/secrets"
            readOnly: true
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
