---
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "fusion.config-sync.fullname" . }}"
  labels:
    {{ include "fusion.config-sync.labels" . | nindent 4 }}
data:
  application.yaml: |
    github:
{{ toYaml .Values.github | nindent 6 }}
    pub:
{{ toYaml .Values.pub | nindent 6 }}
    sub:
{{ toYaml .Values.sub | nindent 6 }}
    logging:
      level:
        root: {{ .Values.logLevelRoot }}
        org:
            springframework:
                cloud:
                    client:
                        discovery: TRACE
    management:
      health:
        solr:
          enabled: false
      endpoints:
        web:
          exposure:
            include: info, health, mappings, ready, prometheus
    jetty:
      server:
        stop:
          timeout: {{ .Values.serverStopTimeout }}
    ribbon:
      zookeeper:
        enabled: false
    spring:
      cloud:
        kubernetes:
          enabled: true
          ribbon:
            enabled: true
        zookeeper:
          connect-string: "{{ include "fusion.zkConnectionString" . }}"
          discovery:
            enabled: false
{{- if $tlsEnabled }}
    server:
      ssl:
        key-store-type: pkcs12
        key-store: /etc/ssl/keystores/keystore.jks
        key-store-password: {{ .Values.tls.keystorePassword }}
        trust-store: /etc/ssl/keystores/truststore.jks
        trust-store-password: {{ .Values.tls.keystorePassword }}
{{- end }}
      sleuth:
        enabled: false
        log:
          slf4j:
            enabled: false
        zipkin:
          enabled: "{{ .Values.zipkinEnabled }}"
          baseUrl: "{{ .Values.zipkinUrl }}"
    accesslog:
      enabled: {{ .Values.accessLogEnabled }}

