{{- $networkPoliciesEnabled := false -}}
{{- if .Values.global -}}
{{- if .Values.global.networkPolicyEnabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}
{{- else if .Values.networkPolicy.enabled -}}
{{- $networkPoliciesEnabled = true -}}
{{- end -}}

{{ if $networkPoliciesEnabled }}
{{ $components:= list "api-gateway" "fusion-admin" "fusion-indexing" "connectors-classic" "connectors-backend" "connectors" "connector-plugin" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fusion.tikaserver.fullname" .  }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "fusion.tikaserver.name" . }}"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "tikaserver"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
{{- range $component := $components }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/component: "{{ $component }}"
{{- end }}
      - podSelector:
          matchLabels:
            spark-role: driver
      - podSelector:
          matchLabels:
            spark-role: executor
      ports:
      - protocol: TCP
        port: 9998
{{ if .Values.networkPolicy.additionalIngressRules }}
{{ toYaml .Values.networkPolicy.additionalIngressRules | nindent 4 }}
{{ end }}
  egress:
# Define egress for DNS lookups
    - to: {{ .Values.networkPolicy.dnsAccess | toYaml | nindent 8 }}
      ports:
      - protocol: UDP
        port: 53
      - protocol: TCP
        port: 53
# This outbound rule is required to talk to the kubernetes API services
    - to: {{ .Values.networkPolicy.kubernetesAccess | toYaml | nindent 8 }}
      ports:
      - protocol: TCP
        port: 443

{{- if .Values.networkPolicy.additionalEgressRules }}
{{ toYaml .Values.networkPolicy.additionalEgressRules | nindent 4 }}
{{ end }}
{{- end }}
