dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.10.1"
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^3.11.0"
- name: "grafana"
  condition: grafana.enabled
  version: "~6.24.1"
  repository:  "https://grafana.github.io/helm-charts"
- name: "prometheus"
  condition: prometheus.enabled
  version: "~15.5.3"
  repository:  "https://prometheus-community.github.io/helm-charts"