---
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}

kind: Service
apiVersion: v1
metadata:
  name: {{ include "fusion.connector-plugin.serviceName" . }}
  labels:
{{ include "fusion.connector-plugin.labels" . | indent 4 }}
{{- if $tlsEnabled }}
    secured: "true"
{{- end }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
spec:
  selector:
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: "{{ .Values.component }}"
    app.kubernetes.io/part-of: "fusion"
  ports:
    - protocol: TCP
      port: {{ .Values.port.external }}
      targetPort: {{ .Values.port.internal }}
  type: ClusterIP
