accessLogEnabled: false
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 70
    type: Resource
  minReplicas: 1
deploymentStrategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  type: RollingUpdate
fusion-common-utils:
  global: {}
image:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  name: config-sync
  repository: lucidworks
  tag: latest
javaToolOptions: ""
keytoolUtils:
  image:
    imagePullPolicy: IfNotPresent
    imagePullSecrets:
    - name: artifactory
    name: keytool-utils
    repository: lucidworks
    tag: v2.0.0
livenessProbe:
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3
logLevelRoot: info
networkPolicy:
  additionalEgressRules: []
  additionalIngressRules: []
  dnsAccess:
  - ipBlock:
      cidr: 0.0.0.0/0
  enabled: false
  kubernetesAccess:
  - ipBlock:
      cidr: 0.0.0.0/0
nodeSelector: {}
pod:
  annotations: {}
podDisruptionBudget:
  maxUnavailable: 1
port: 5150
preStopSleepTime: 10
rbac:
  create: true
readinessProbe:
  failureThreshold: 12
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3
replicaCount: 1
resources: {}
securityContext:
  fsGroup: 8764
  runAsNonRoot: true
  runAsUser: 8764
serverStopTimeout: 5000
service:
  annotations: {}
  port: 5150
  targetPort: 5150
  type: ClusterIP
springProfiles: kubernetes,jwt,fusion,pub
tls:
  caSecret:
    name: ""
  certSecret:
    name: ""
  clusterDomain: svc.cluster.local
  duration: 8760h
  enabled: false
  generateCert: true
  generateJKS: true
  issuerRef:
    kind: Issuer
    name: fusion-ca-issuer
  keystorePassword: changeit
  renewBefore: 8464h
zipkinEnabled: "false"
zipkinUrl: localhost:9411
zkPort: 2181
zkReplicaCount: 3
zkTLSPort: 2281
