{{- if or .Values.components.pulsar_manager .Values.extra.pulsar_manager }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "pulsar.fullname" . }}-{{ .Values.pulsar_manager.component }}"
  namespace: {{ template "pulsar.namespace" . }}
  labels:
    {{- include "pulsar.standardLabels" . | nindent 4 }}
    component: {{ .Values.pulsar_manager.component }}
  annotations:
{{ toYaml .Values.pulsar_manager.service.annotations | indent 4 }}
spec:
  type: {{ .Values.pulsar_manager.service.type }}
  ports:
    - name: server
      port: {{ .Values.pulsar_manager.port }}
      protocol: TCP
  selector:
    app: {{ template "pulsar.name" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.pulsar_manager.component }}
{{- end }}
