apiVersion: v2
name: fusion-monitoring
version: 1.0.0
appVersion: 1.0.0
description: A helm chart to install Prometheus and Grafana for monitoring Lucidworks Fusion
keywords:
  - prometheus
  - grafana
maintainers:
  - email: ian.thebridge@lucidworks.com
    name: Ian Thebridge
dependencies:
- name: prometheus
  version: 10.5.2
  repository: https://prometheus-community.github.io/helm-charts
  tags:
    - prometheus
- name: grafana
  version: 5.0.3
  repository: https://grafana.github.io/helm-charts
  tags:
    - grafana