---
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}
{{- $jsonOutput := ( eq (include "fusion.loggingJSONOutput" .) "true" ) }}
{{- $logstashHost := (include "fusion.logstashHost" .) -}}
{{- $logPulsar := ( eq (include "fusion.loggingDisablePulsar" .) "false" ) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "fusion.ml-model-service.fullname" .  }}"
  labels:
    {{ include "fusion.ml-model-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "ml-model-service"
      app.kubernetes.io/part-of: "fusion"
  template:
    metadata:
      name: "{{ include "fusion.ml-model-service.fullname" .  }}"
      labels:
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: "ml-model-service"
        app.kubernetes.io/part-of: "fusion"
      annotations:
        {{ toYaml .Values.pod.annotations | nindent 8 }}
    spec:
      volumes:
        - name: "shareddir"
          emptyDir: {}
        {{- if .Values.gcs.pretrained.enabled }}
        - name: gcs-pretrained-secret
          secret:
            secretName: {{ .Values.gcs.pretrained.gcsSecret.secretName }}
        {{- end}}
{{- if $tlsEnabled }}
{{ $params := dict "tlsServiceName" "ml-model-service" "Release" $.Release "global" $.Values.global "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils }}
{{ include "fusion.tls.volumes" $params | indent 8 }}
{{- end }}
{{- if .Values.securityContext }}
      securityContext:
{{- .Values.securityContext | toYaml | nindent 8 }}
{{- end }}
      serviceAccountName: "{{ .Values.rbac.serviceAccountName | default ( include "fusion.ml-model-service.fullname" . ) }}"
      imagePullSecrets:
        {{ toYaml .Values.image.imagePullSecrets | nindent 8 }}
      {{ if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{ end }}
      {{ if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{ end }}
      {{ if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{ end }}
      {{ if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{ end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
        {{ tpl (toYaml .Values.affinity) . | nindent 8 }}
    {{- end }}
      initContainers:
{{- if $tlsEnabled -}}
{{ $params := dict "tlsServiceName" "ml-model-service" "Release" $.Release "global" $.Values.global "securityContext" $.Values.securityContext "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils }}
{{ include "fusion.tls.init-container-v2" $params | indent 8 }}
{{- end }}
{{- if eq .Values.modelRepoImpl "fusion" }}
{{- include "fusion.initContainers.checkAdmin-v2" . | nindent 8 }}
{{ end }}
      containers:
      - name: java-service
        image: "{{ .Values.javaService.repository | default .Values.image.repository }}/{{ .Values.javaService.imageName }}:{{ .Values.javaService.tag | default .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
          {{- if .Values.gcs.pretrained.enabled }}
          - name: gcs-pretrained-secret
            mountPath: {{ .Values.gcs.pretrained.gcsSecret.path }}
            readOnly: true
          {{- end}}
          - mountPath: /tmp
            name: shareddir
{{ if $tlsEnabled }}
          - name: "keystore-volume"
            mountPath: "/etc/ssl/keystores"
{{ end }}
        env:
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.javaToolOptions }}
{{- if $tlsEnabled }} -Dlogging.config=classpath:logback-kube-tls.xml {{- else }} -Dlogging.config=classpath:logback-kube.xml {{- end -}}
{{- if $tlsEnabled }} -Djavax.net.ssl.trustStore=/etc/ssl/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword={{ .Values.tls.keystorePassword }} -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true -Dzookeeper.ssl.keyStore.location=/etc/ssl/keystores/keystore.jks -Dzookeeper.ssl.trustStore.location=/etc/ssl/keystores/truststore.jks -Dzookeeper.ssl.keyStore.password={{ .Values.tls.keystorePassword }} -Dzookeeper.ssl.trustStore.password={{ .Values.tls.keystorePassword }}{{- end -}}
"
          {{ if $logstashHost }}
          - name: LOGSTASH_HOST
            value: "{{ $logstashHost }}"
          {{ end }}
          - name: "PULSAR_TENANT"
            value: "{{ include "fusion.ml-model-service.kubeNamespace" . }}"
          - name: "PULSAR_SERVICE_URL"
            value: "{{ include "fusion.ml-model-service.pulsarServiceUrl" . }}"
          - name: "COMPONENT"
            value: "ml-model-service"
        args:
          - "--spring.profiles.active=kubernetes,jwt{{- if $tlsEnabled }},tls{{- end }}{{- if $jsonOutput }},logjson{{- end }}{{- if $logstashHost }},logstash{{- end }}{{- if $logPulsar }},logpulsar{{- end }}"
          - "--spring.cloud.kubernetes.config.name={{ include "fusion.ml-model-service.fullname" . }}"
        ports:
          - containerPort: 6565
            name: grpc
          - containerPort: {{ .Values.port }}
            name: "jetty"
        livenessProbe:
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          httpGet:
            path: /actuator/health
            port: jetty
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}
        readinessProbe:
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          httpGet:
            path: /actuator/health
            port: jetty
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}

        resources:
          {{ toYaml .Values.javaService.resources | nindent 10 }}