{{- if .Values.rbac.create }}
---
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}


apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "fusion.ml-model-service.fullname" . }}"

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: "{{ include "fusion.ml-model-service.fullname" . }}"
rules:
- apiGroups: [""]
  resources: [ "pods", "services", "configmaps", "endpoints", "pods/log"]
  verbs: [ "get", "list", "watch", "patch"]
{{- if $tlsEnabled }}
- apiGroups: [ "cert-manager.io" ]
  resources: [ "certificates" ]
  verbs: [ "get", "create", "delete" ]
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get" ]
{{- end }}

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "fusion.ml-model-service.fullname" . }}"
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: "{{ include "fusion.ml-model-service.fullname" . }}"
  apiGroup: ""
roleRef:
  kind: Role
  name: "{{ include "fusion.ml-model-service.fullname" . }}"
  apiGroup: rbac.authorization.k8s.io

{{- end }}
