apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fusion-jupyter.fullname" . }}
  labels:
{{ include "fusion-jupyter.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fusion-jupyter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fusion-jupyter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: "{{ include "fusion-jupyter.fullname" . }}"
      {{- if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ tpl (toYaml .Values.affinity) . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          volumeMounts:
            - name: {{ include "fusion-jupyter.fullname" . }}-storage-notebook
              mountPath: {{ .Values.mountPath.notebook  }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          lifecycle:
            postStart:
              exec:
                command: ["./copy_dir.sh"]
          env:
            - name: WORK_DIR
              value: {{ .Values.mountPath.notebook }}
            - name: SOLR_ZKHOST
              value: {{ template "jupyter.zkConnection" . }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ include "fusion-jupyter.fullname" . }}-storage-notebook
          persistentVolumeClaim:
            claimName: "{{ include "fusion-jupyter.fullname" . }}-pvc"
