apiVersion: v2
appVersion: "5"
dependencies:
- name: fusion-common-utils
  repository: https://charts.lucidworks.com/
  version: 1.5.1
description: A helm chart to install the rules-ui component
keywords:
- fusion
- rules-ui
- rules
maintainers:
- email: dmitriy.lyner@lucidworks.com
  name: Dmitriy Lyner
- email: graham.holt@lucidworks.com
  name: Graham Holt
name: rules-ui
version: 1.4.1
