---
{{- $tlsEnabled := ( eq (include "fusion.tls.enabled" .) "true" ) -}}
{{- $jsonOutput := ( eq (include "fusion.loggingJSONOutput" .) "true" ) }}
{{- $logstashHost := (include "fusion.logstashHost" .) -}}
{{- $logPulsar := ( eq (include "fusion.loggingDisablePulsar" .) "false" ) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fusion.job-launcher.fullname" .  }}
  labels:
    {{ include "fusion.job-launcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy }}
  strategy:
    {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: "job-launcher"
      app.kubernetes.io/part-of: "fusion"
  template:
    metadata:
      name: {{ include "fusion.job-launcher.fullname" .  }}
      labels:
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: "job-launcher"
        app.kubernetes.io/part-of: "fusion"
      annotations:
        {{ toYaml .Values.pod.annotations | nindent 8 }}
    spec:
{{- if .Values.securityContext }}
      securityContext:
{{- .Values.securityContext | toYaml | nindent 8 }}
{{- end }}
      serviceAccountName: "{{ .Values.rbac.serviceAccountName | default ( include "fusion.job-launcher.fullname" . ) }}"
      {{ if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{ end }}
      {{ if .Values.tolerations }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}
      {{ end }}
      {{ if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{ end }}
      {{ if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{ end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
        {{ tpl (toYaml .Values.affinity) . | nindent 8 }}
    {{- end }}
      imagePullSecrets:
        {{ toYaml .Values.image.imagePullSecrets | nindent 8 }}
      volumes:
        - name: secrets
          secret:
            secretName: service-account-key
            items:
              - key: sa
                path: service-account-key
        - name: work-dir
          emptyDir: {}
        - name: tmp
          emptyDir: {}
{{- if $tlsEnabled }}
{{ $params := dict "tlsServiceName" ( include "fusion.job-launcher.serviceName" . ) "Release" $.Release "global" $.Values.global "tls" $.Values.tls  "keytoolUtils" $.Values.keytoolUtils }}
{{ include "fusion.tls.volumes" $params | indent 8 }}
{{- end }}

      initContainers:
{{- if $tlsEnabled -}}
{{ $params := dict "tlsServiceName" ( include "fusion.job-launcher.serviceName" . ) "Release" $.Release "global" $.Values.global "tls" $.Values.tls "securityContext" $.Values.securityContext "keytoolUtils" $.Values.keytoolUtils }}
{{ include "fusion.tls.init-container-v2" $params | indent 8 }}
{{- end }}
      containers:
      - name: job-launcher
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          privileged: false
        volumeMounts:
          - name: secrets
            mountPath: "/etc/secrets"
            readOnly: true
          - name: tmp
            mountPath: /tmp
          - name: work-dir
            mountPath: /app/var
{{ if $tlsEnabled }}
          - name: "keystore-volume"
            mountPath: "/etc/ssl/keystores"
{{ end }}
        args:
          - "--spring.profiles.active={{ include "fusion.job-launcher.springProfs" . }}{{- if $tlsEnabled }},tls{{- end }}{{- if $jsonOutput }},logjson{{- end }}{{- if $logstashHost }},logstash{{- end }}{{- if $logPulsar }},logpulsar{{- end }}"
          - "--spring.cloud.kubernetes.config.sources[0].name={{ include "fusion.job-launcher.fullname" . }}"
          {{- range $index, $name := .Values.configSources }}
          - "--spring.cloud.kubernetes.config.sources[{{ add $index 1 }}].name={{ $name }}"
          {{- end }}
          - "--spring.cloud.kubernetes.secrets.paths=/etc/secrets"
        {{- if .Values.secrets }}
        envFrom:
          - secretRef:
              name: {{ template "fusion.job-launcher.fullname" . }}
        {{- end }}
        ports:
          - containerPort: {{ .Values.port }}
            name: "jetty"
        livenessProbe:
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          httpGet:
            path: /actuator/health
            port: jetty
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}

        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          httpGet:
            path: /actuator/health
            port: "jetty"
{{- if $tlsEnabled }}
            scheme: HTTPS
{{- end }}

        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep {{ .Values.preStopSleepTime }}"]
        env:
          - name: "JAVA_TOOL_OPTIONS"
            value: "{{ .Values.javaToolOptions }}
{{- if $tlsEnabled }} -Dlogging.config=classpath:logback-kube-tls.xml {{- else }} -Dlogging.config=classpath:logback-kube.xml {{- end -}}
{{- if $tlsEnabled }} -Djavax.net.ssl.trustStore=/etc/ssl/keystores/truststore.jks -Djavax.net.ssl.trustStorePassword={{ .Values.tls.keystorePassword }} -Dzookeeper.clientCnxnSocket=org.apache.zookeeper.ClientCnxnSocketNetty -Dzookeeper.client.secure=true -Dzookeeper.ssl.keyStore.location=/etc/ssl/keystores/keystore.jks -Dzookeeper.ssl.trustStore.location=/etc/ssl/keystores/truststore.jks -Dzookeeper.ssl.keyStore.password={{ .Values.tls.keystorePassword }} -Dzookeeper.ssl.trustStore.password={{ .Values.tls.keystorePassword }}{{- end -}}
"
          - name: "PULSAR_TENANT"
            value: "{{ include "fusion.job-launcher.kubeNamespace" . }}"
          - name: "PULSAR_SERVICE_URL"
            value: "{{ include "fusion.job-launcher.pulsarServiceUrl" . }}"
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          {{ if $logstashHost }}
          - name: LOGSTASH_HOST
            value: "{{ $logstashHost }}"
          {{ end }}
          - name: "COMPONENT"
            value: "job-launcher"
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
