apiVersion: v2
appVersion: "5"
description: A helm chart to install details for the classification service
keywords:
- fusion
- ml
- classification
maintainers:
- email: binoy.dalal1@lucidworks.com
  name: Binoy Dalal
name: classification
type: application
version: 1.0.2
